"""Gauss-type baselines with an error estimate for experiment E3 of the Clenshaw–Curtis study.

Two baselines answer the question "is it the rule or the nesting?":

* ``gauss_patterson`` — the nested Gauss–Kronrod–Patterson sequence (Patterson 1968) with
  1, 3, 7, 15, 31, 63, 127 points, run *non-adaptively* with exactly the stopping test of
  ``clenshaw_curtis`` (first k ≥ 2 with |I_k − I_{k−1}| ≤ tol·max(1, |I_k|)). Level k has
  N_k = 2^{k+1} − 1 points, and every node of level k is a node of level k + 1, so a run that
  stops at level K costs N_K evaluations — the same nesting economics as CC (2^{k+1} + 1 points),
  but with a Gauss-type rule of degree ≈ 3N/2 instead of N.
* ``quadpack_qags`` — ``scipy.integrate.quad``: QUADPACK's QAGS, adaptive Gauss–Kronrod (G10/K21)
  bisection with Wynn's ε-algorithm extrapolation. This is the standard production integrator.

Patterson extension (Patterson 1968; Gautschi 2004, §3.1.2). Given a symmetric node set X with
n points, the extension adds n + 1 points so that the interpolatory rule on all N = 2n + 1
points has the highest degree. Its node polynomial Π(x) = ∏_{x_j ∈ X}(x − x_j)·q(x) must satisfy
∫₋₁¹ Π(x) p(x) dx = 0 for every p of degree ≤ n, so (with Legendre polynomials P_i)

    Π = Σ_{i = n+1}^{N} π_i P_i,   Π(x_j) = 0 for x_j ∈ X,   π_N = 1.                   (E)

By symmetry only the i with the parity of N enter, and only the x_j > 0 give conditions, which
makes (E) a square system of (n + 1)/2 (n odd) or n/2 + 1 (n even) equations. The new nodes are
the roots of Π between consecutive old nodes; they are found by sign-change bracketing and
bisection on Π. The interpolatory weights are w_k = ∫ ℓ_k = ∫ Π(x)/((x − x_k)Π'(x_k)) dx,
integrated exactly by a Gauss–Legendre rule. The rule on N points is exact to degree 3n + 1
(3n + 2 for odd n, by symmetry). Starting from X = {0} the sequence is 1 → 3 (= Gauss G₃) →
7 (= Kronrod K₇ of G₃) → 15 → 31 → 63 → 127. The same routine applied to Gauss G₇ and G₁₀
reproduces QUADPACK's K₁₅ and K₂₁ (tested against SciPy's tables).

# NOTE: everything is computed in numpy ``longdouble``, which is IEEE binary128 (113-bit
# significand) on aarch64 Linux. The extension is ill-conditioned in a structural way: the
# envelope of the node polynomial grows near ±1 (at 63 old points |ω| spans 5.7e-5 … 1.7e2), so
# the interior nodes have a small effect on the conditions (E) and lose digits. In binary128 three
# independent formulations ((E); q ⊥ P_{≤n} in the ω-weighted inner product; Newton on the node
# positions) agree to ≤ 3e-28 up to 63 points and to 1.9e-17 (the first two) at 127 points.
# They fail at the 127 → 255 extension. The sequence therefore stops at 127 points
# (MAX_LEVEL = 6); the 255- and 511-point rules need more than binary128 precision.
# Because ``longdouble`` is not binary128 on every platform, the rules are stored in
# ``patterson_rules.json`` (17 significant digits) and regenerated by ``python baselines.py``
# where binary128 is available; the tests check the stored file in double precision
# (exactness degree, positive weights, exact nesting) and against a fresh binary128 computation.

References:
    T. N. L. Patterson, "The optimum addition of points to quadrature formulae", Math. Comp. 22
    (1968) 847–856.
    A. S. Kronrod, "Nodes and weights of quadrature formulas", Consultants Bureau, 1965.
    W. Gautschi, "Orthogonal Polynomials: Computation and Approximation", OUP 2004, §3.1.2.
    R. Piessens, E. de Doncker-Kapenga, C. Überhuber, D. Kahaner, "QUADPACK", Springer 1983.
"""

from __future__ import annotations

import json
import math
import warnings
from collections.abc import Callable
from functools import cache
from pathlib import Path
from typing import Any

import numpy as np
from numpy.typing import NDArray

from numopt.core.counting import Counted, scalar_problem
from numopt.core.types import Problem, Result, Step

LD = np.longdouble
HERE = Path(__file__).resolve().parent
RULES_FILE = HERE / "patterson_rules.json"
#: Highest Patterson level computed reliably in binary128: 2^{MAX_LEVEL+1} − 1 = 127 points.
MAX_LEVEL = 6

# --------------------------------------------------------------------------------------
# Patterson extension in binary128
# --------------------------------------------------------------------------------------


def _require_binary128() -> None:
    if np.finfo(LD).nmant < 112:
        raise RuntimeError(
            f"numpy longdouble has {np.finfo(LD).nmant} mantissa bits here, not binary128 (112); "
            f"use the stored {RULES_FILE.name}"
        )


def _legendre_table(degree: int, x: NDArray[Any]) -> NDArray[Any]:
    """P_0(x), …, P_degree(x) by the three-term recurrence; shape (degree + 1, x.size)."""
    x = np.asarray(x, dtype=LD)
    P = np.empty((degree + 1, x.size), dtype=LD)
    P[0] = 1
    if degree >= 1:
        P[1] = x
    for i in range(2, degree + 1):
        P[i] = ((2 * i - 1) * x * P[i - 1] - (i - 1) * P[i - 2]) / i
    return P


def _legendre_sum(coef: NDArray[Any], x: NDArray[Any]) -> NDArray[Any]:
    """Σ_i coef[i]·P_i(x) for a vector x (recurrence, no table)."""
    x = np.asarray(x, dtype=LD)
    p0, p1 = np.ones_like(x), x.copy()
    s = coef[0] * p0 + coef[1] * p1
    for i in range(2, coef.size):
        p0, p1 = p1, ((2 * i - 1) * x * p1 - (i - 1) * p0) / i
        if coef[i] != 0:
            s = s + coef[i] * p1
    return s


def _solve(A: NDArray[Any], b: NDArray[Any]) -> NDArray[Any]:
    """Gaussian elimination with partial pivoting in longdouble (LAPACK has no binary128)."""
    A, b = A.astype(LD).copy(), b.astype(LD).copy()
    n = b.size
    for p in range(n):
        piv = p + int(np.argmax(np.abs(A[p:, p])))
        if piv != p:
            A[[p, piv]], b[[p, piv]] = A[[piv, p]], b[[piv, p]]
        f = A[p + 1 :, p] / A[p, p]
        A[p + 1 :, p:] -= np.outer(f, A[p, p:])
        b[p + 1 :] -= f * b[p]
    x = np.empty(n, dtype=LD)
    for p in range(n - 1, -1, -1):
        x[p] = (b[p] - A[p, p + 1 :] @ x[p + 1 :]) / A[p, p]
    return x


def gauss_legendre_ld(m: int) -> tuple[NDArray[Any], NDArray[Any]]:
    """m-point Gauss–Legendre rule in longdouble (Newton on P_m from Tricomi's start), decreasing."""
    i = np.arange(1, m + 1, dtype=LD)
    x = np.cos(np.pi * (i - LD(0.25)) / (m + LD(0.5))).astype(LD)
    for _ in range(10):
        P = _legendre_table(m, x)
        x = x - P[m] / (m * (x * P[m] - P[m - 1]) / (x * x - 1))
    P = _legendre_table(m, x)
    dp = m * (x * P[m] - P[m - 1]) / (x * x - 1)
    return x, 2 / ((1 - x * x) * dp * dp)


def kronrod_patterson_extension(old: NDArray[Any]) -> NDArray[Any]:
    """The n + 1 new nodes (decreasing, longdouble) of the optimal extension of the symmetric set ``old``.

    Solves (E) of the module docstring and brackets one root of Π in each gap between consecutive
    old nodes (and between the largest old node and 1). Raises RuntimeError if a gap does not
    contain exactly one sign change of Π (no real interlacing extension, or lost precision).
    """
    old = np.sort(np.asarray(old, dtype=LD))[::-1]
    n = old.size
    if not np.array_equal(old, -old[::-1]):
        raise ValueError("the old node set must be symmetric")
    N = 2 * n + 1
    idx = np.array([i for i in range(n + 1, N + 1) if i % 2 == N % 2])  # parity of N (odd)
    pos = old[old > 0]  # (r,)
    B = _legendre_table(N, pos)[idx].T  # (r, len(idx)): Π(x_j) = 0
    A = np.vstack([B, np.eye(idx.size, dtype=LD)[-1:]])  # + normalization π_N = 1
    rhs = np.zeros(idx.size, dtype=LD)
    rhs[-1] = 1
    coef = np.zeros(N + 1, dtype=LD)
    coef[idx] = _solve(A, rhs)
    # Gaps in (0, 1): (pos_1, 1), (pos_2, pos_1), …, (0, pos_last). If 0 is not an old node, it is
    # a new node (Π is odd) and the last gap (0, pos_last) holds no positive root.
    ends = np.concatenate([[LD(1)], pos, [LD(0)]])
    lo, hi = ends[1:], ends[:-1]
    zero_is_new = not np.any(old == 0)
    if zero_is_new:
        lo, hi = lo[:-1], hi[:-1]
    s = np.arange(1, 65, dtype=LD) / 65  # 64 interior sample points per gap
    grid = lo[:, None] + (hi - lo)[:, None] * s[None, :]  # (gaps, 64)
    v = _legendre_sum(coef, grid.ravel()).reshape(grid.shape)
    change = np.sign(v[:, 1:]) * np.sign(v[:, :-1]) < 0
    if not np.all(change.sum(axis=1) == 1):
        raise RuntimeError(f"no interlacing real extension found: sign changes {change.sum(1)}")
    rows = np.arange(grid.shape[0])
    j = np.argmax(change, axis=1)
    a, b, fa = grid[rows, j], grid[rows, j + 1], v[rows, j]
    for _ in range(120):  # bisection to the binary128 resolution (2^-120 < ulp)
        m = 0.5 * (a + b)
        fm = _legendre_sum(coef, m)
        left = np.sign(fm) == np.sign(fa)
        a, fa, b = np.where(left, m, a), np.where(left, fm, fa), np.where(left, b, m)
    r = 0.5 * (a + b)
    new = np.concatenate([r, -r] + ([np.zeros(1, dtype=LD)] if zero_is_new else []))
    return np.sort(new)[::-1]


def interpolatory_weights(nodes: NDArray[Any]) -> NDArray[Any]:
    """w_k = ∫₋₁¹ ℓ_k(x) dx for the Lagrange basis ℓ_k on ``nodes`` (longdouble).

    ℓ_k(y) = ∏_{j≠k} (y − x_j)/(x_k − x_j), integrated exactly by a Gauss rule with
    M ≥ (N + 1)/2 points (degree N − 1); every factor is scaled by 2 to keep the products O(1).
    """
    x = np.asarray(nodes, dtype=LD)
    N = x.size
    M = (N + 3) // 2
    M += M % 2  # even M: the Gauss nodes avoid 0 and the small Gauss sets inside the sequence
    y, W = gauss_legendre_ld(M)
    D = 2 * (y[None, :] - x[:, None])  # (N, M)
    if np.min(np.abs(D)) < 1e-8:
        raise RuntimeError("a Gauss node coincides with a rule node")
    Pi_y = np.prod(D, axis=0)  # (M,) = 2^N Π(y)
    Dk = 2 * (x[:, None] - x[None, :])
    np.fill_diagonal(Dk, 1)
    dPi = np.prod(Dk, axis=1)  # (N,) = 2^{N−1} Π'(x_k)
    return (W[None, :] * Pi_y[None, :] / D).sum(axis=1) / dPi


def compute_patterson_rules(max_level: int = MAX_LEVEL) -> list[tuple[NDArray[Any], NDArray[Any]]]:
    """[(nodes, weights)] for levels 0..max_level (1, 3, 7, …, 2^{max_level+1} − 1 points), binary128."""
    _require_binary128()
    nodes = np.zeros(1, dtype=LD)
    rules = [(nodes, np.array([2], dtype=LD))]
    for _ in range(max_level):
        nodes = np.sort(np.concatenate([nodes, kronrod_patterson_extension(nodes)]))[::-1]
        rules.append((nodes, interpolatory_weights(nodes)))
    return rules


def write_rules_file() -> None:
    """Store the rules as decimal strings with 17 significant digits (round-trip exact in double)."""
    rules = compute_patterson_rules()
    payload = {
        "note": "Gauss–Kronrod–Patterson rules on [-1, 1], nodes decreasing; computed in binary128 "
        "by baselines.compute_patterson_rules; 17 significant digits (exact double round-trip).",
        "levels": [
            {
                "n_points": int(x.size),
                "nodes": [f"{float(v):.17g}" for v in x],
                "weights": [f"{float(v):.17g}" for v in w],
            }
            for x, w in rules
        ],
    }
    RULES_FILE.write_text(json.dumps(payload, indent=1) + "\n")


@cache
def patterson_rules() -> tuple[tuple[NDArray[np.float64], NDArray[np.float64]], ...]:
    """The stored rules in double precision: ((nodes, weights), …) for 1, 3, …, 127 points."""
    data = json.loads(RULES_FILE.read_text())
    return tuple(
        (
            np.array([float(v) for v in lev["nodes"]]),
            np.array([float(v) for v in lev["weights"]]),
        )
        for lev in data["levels"]
    )


# --------------------------------------------------------------------------------------
# The two methods
# --------------------------------------------------------------------------------------


def gauss_patterson(
    problem: Problem | Callable[[float], float], *, tol: float, max_level: int = MAX_LEVEL
) -> Result:
    """Non-adaptive nested Gauss–Kronrod–Patterson quadrature with the stopping test of CC.

    Step k applies the N_k = 2^{k+1} − 1 point rule on [a, b]; converged=True at the first k ≥ 2
    with |I_k − I_{k−1}| ≤ tol·max(1, |I_k|); converged=False after ``max_level`` or on a
    non-finite value. f is cached by abscissa, so a run stopping at level K costs N_K evaluations.
    """
    prob = scalar_problem(problem)
    if not (math.isfinite(tol) and tol > 0):
        raise ValueError(f"tol must be a positive finite number, got {tol!r}")
    if not 2 <= max_level <= MAX_LEVEL:
        raise ValueError(f"max_level must be in [2, {MAX_LEVEL}], got {max_level}")
    a, b = (float(v) for v in prob.domain)
    half, mid = 0.5 * (b - a), 0.5 * (a + b)
    exact = None if prob.exact is None else float(prob.exact)
    counted = Counted(prob.f)
    cache_: dict[float, float] = {}

    def f(x: float) -> float:
        if x not in cache_:
            try:
                with np.errstate(all="ignore"):
                    cache_[x] = float(counted(x))
            except (ArithmeticError, ValueError):  # as clenshaw_curtis: a failed f is NaN
                cache_[x] = math.nan
        return cache_[x]

    trace: list[Step] = []
    est, err_est = math.nan, None
    extra: dict[str, Any] = {}
    rules = patterson_rules()
    for k in range(max_level + 1):
        t, w = rules[k]
        x = mid + half * t  # (N_k,) the same doubles at every level, so the cache is exact
        n_before = counted.n
        vals = [f(float(xi)) for xi in x]
        prev, est = est, math.fsum((half * w * np.array(vals)).tolist())
        if k > 0:
            err_est = abs(est - prev)
        error = None if exact is None else abs(est - exact)
        trace.append(
            Step(
                k,
                est,
                est,
                info={
                    "estimate": est,
                    "error": error,
                    "err_est": err_est,
                    "n_points": int(t.size),
                    "new_nodes": counted.n - n_before,
                },
            )
        )
        extra = {"exact": exact, "error": error, "err_est": err_est, "n_points": int(t.size)}
        if not (math.isfinite(est) and all(math.isfinite(v) for v in vals)):
            return Result("gauss_patterson", est, est, False, "non-finite value", k, counted.n,
                          trace=trace, extra=extra)  # fmt: skip
        if k >= 2 and err_est is not None and err_est <= tol * max(1.0, abs(est)):
            return Result("gauss_patterson", est, est, True, f"passed with {t.size} points", k,
                          counted.n, trace=trace, extra=extra)  # fmt: skip
    return Result("gauss_patterson", est, est, False,
                  f"reached the largest rule ({rules[max_level][0].size} points)", max_level,
                  counted.n, trace=trace, extra=extra)  # fmt: skip


def quadpack_qags(
    problem: Problem | Callable[[float], float],
    *,
    tol: float,
    epsabs: float | None = None,
    limit: int = 200,
) -> Result:
    """``scipy.integrate.quad`` (QUADPACK QAGS: adaptive G10/K21 with ε-extrapolation).

    Requested accuracy |I − I_est| ≤ max(epsabs, tol·|I_est|). The default epsabs = tol makes this
    max(tol, tol·|I|) = tol·max(1, |I|), the acceptance scale that every method in E3 is judged on
    and the stopping scale of ``clenshaw_curtis``. converged = QUADPACK's ier == 0. The cost is the
    number of f calls (each subinterval costs 21; equal to QUADPACK's ``neval``).
    """
    from scipy.integrate import quad

    prob = scalar_problem(problem)
    a, b = (float(v) for v in prob.domain)
    counted = Counted(prob.f)
    eps_abs = tol if epsabs is None else epsabs
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        out = quad(counted, a, b, epsabs=eps_abs, epsrel=tol, limit=limit, full_output=1)
    est, abserr, info = float(out[0]), float(out[1]), out[2]
    converged = len(out) == 3  # quad appends a message only when ier > 0
    exact = None if prob.exact is None else float(prob.exact)
    extra = {
        "exact": exact,
        "error": None if exact is None else abs(est - exact),
        "err_est": abserr,
        "neval": int(info["neval"]),
        "subintervals": int(info["last"]),
        "message": "" if converged else str(out[3]).splitlines()[0],
    }
    msg = "QUADPACK ier = 0" if converged else f"QUADPACK: {extra['message']}"
    # QUADPACK is a black box here: the trace holds one step, the final estimate.
    trace = [Step(0, est, est, info={"estimate": est, "error": extra["error"], "err_est": abserr})]
    return Result("quadpack_qags", est, est, converged, msg, int(info["last"]), counted.n,
                  trace=trace, extra=extra)  # fmt: skip


if __name__ == "__main__":
    write_rules_file()
    for x, w in patterson_rules():
        print(x.size, float(w.min()), math.fsum(w.tolist()))
